name: CI for python flask

on:
  push:
    branches: main
  pull_request:
    branches: main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       
     - name: building dockerfile
       run: docker build -t trial-app .

     - name: Login into dockerhub
       uses: docker/login-action@v2
       with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

     - name: pushing docker images
       run: |
        docker tag trial-app akash300/trial-app
        docker push akash300/trial-app
    
 
  
